/*
 * Copyright (c) 2022-2026 LabKey Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.labkey.test.tests.assay;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.labkey.test.BaseWebDriverTest;
import org.labkey.test.Locator;
import org.labkey.test.Locators;
import org.labkey.test.TestFileUtils;
import org.labkey.test.TestTimeoutException;
import org.labkey.test.WebDriverWrapper;
import org.labkey.test.categories.Assays;
import org.labkey.test.categories.Daily;
import org.labkey.test.components.assay.AssayConstants;
import org.labkey.test.pages.ReactAssayDesignerPage;
import org.labkey.test.pages.files.WebDavPage;
import org.labkey.test.params.FieldDefinition;
import org.labkey.test.util.DataRegionTable;
import org.labkey.test.util.Log4jUtils;
import org.labkey.test.util.QCAssayScriptHelper;
import org.labkey.test.util.RReportHelper;
import org.labkey.test.util.ScriptInvocationLogHelper;

import java.io.File;
import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.labkey.test.pages.ReactAssayDesignerPage.ScriptFileEvent.Edit;
import static org.labkey.test.pages.ReactAssayDesignerPage.ScriptFileEvent.Import;
import static org.labkey.test.util.PermissionsHelper.FOLDER_ADMIN_ROLE;

@Category({Assays.class, Daily.class})
@BaseWebDriverTest.ClassTimeout(minutes = 4)
public class AssayTransformWarningTest extends BaseWebDriverTest
{
    public static final File JAVA_TRANSFORM_SCRIPT = TestFileUtils.getSampleData("qc/transformWarning.jar");
    public static final File R_TRANSFORM_SCRIPT = TestFileUtils.getSampleData("qc/assayTransformWarning.R");
    public static final File R_TRANSFORM_ERROR_SCRIPT = TestFileUtils.getSampleData("qc/assayTransformError.R");
    public static final File JAVA_INVALID_TRANSFORM_SCRIPT = TestFileUtils.getSampleData("qc/src/org/labkey/AssayTransformNoOp.java");
    public static final Locator.XPathLocator ASSAY_NAME_FIELD_LOCATOR = Locator.name("Name");

    @Override
    public List<String> getAssociatedModules()
    {
        return Arrays.asList("assay");
    }

    @Override
    protected String getProjectName()
    {
        return getClass().getSimpleName() + " Project";
    }

    @Override
    protected BrowserType bestBrowser()
    {
        return BrowserType.CHROME;
    }

    @Override
    public void doCleanup(boolean afterTest) throws TestTimeoutException
    {
        _containerHelper.deleteProject(getProjectName(), afterTest);
    }

    @Before
    public void preTest()
    {
        goToProjectHome();
    }

    @BeforeClass
    public static void initTest()
    {
        AssayTransformWarningTest init = getCurrentTest();
        init.doInit();
    }

    protected void doInit()
    {
        new RReportHelper(this).ensureRConfig();
        new QCAssayScriptHelper(this).ensureEngineConfig();

        _containerHelper.createProject(getProjectName(), "Assay");
    }

    @Test
    public void testJavaTransformWarning() throws Exception
    {
        String assayName = "transformWarningJar";
        String importData = "ParticipantId\nJavaWarned";
        String runName = "java transform run";

        _assayHelper.createAssayDesign("General", assayName)
                .addTransformScript(JAVA_TRANSFORM_SCRIPT, true)
                .clickFinish();

        clickAndWait(Locator.linkWithText(assayName));
        clickButton("Import Data");
        clickButton("Next");
        setFormElement(ASSAY_NAME_FIELD_LOCATOR, runName);
        setFormElement(AssayConstants.TEXT_AREA_DATA_COLLECTOR_LOCATOR, importData);

        clickButton("Save and Finish");
        assertElementPresent(Locators.labkeyError.containing("Inline warning from Java transform."));
        assertElementPresent(Locator.linkWithText("Warning link").withAttribute("href", "http://www.labkey.test"));

        File extraFile1 = clickAndWaitForDownload(Locator.linkContainingText("test1.txt"));
        File extraFile2 = clickAndWaitForDownload(Locator.linkContainingText("test2.tsv"));

        assertEquals("Wrong text in file generated by transform", "This is test file 1 (Java).", TestFileUtils.getFileContents(extraFile1).trim());
        assertEquals("Wrong text in file generated by transform", "This is test file 2 (Java).", TestFileUtils.getFileContents(extraFile2).trim());

        clickButton("Proceed");

        clickAndWait(Locator.linkWithText(runName), longWaitForPage);

        DataRegionTable table = new DataRegionTable("Data", this);
        assertEquals(1, table.getDataRowCount());
        assertTextPresent("JavaWarned");
    }

    @Test
    public void testRTransformWarning()
    {
        String assayName = "transformWarningR";
        String importData = "ParticipantId\nRWarned";
        String runName = "R transform run";

        ReactAssayDesignerPage assayDesignerPage = _assayHelper.createAssayDesign("General", assayName)
            .addTransformScript(R_TRANSFORM_SCRIPT, true);
        assayDesignerPage.goToRunFields()
            .addField("myFile")
            .setLabel("My File")
            .setType(FieldDefinition.ColumnType.File);
        assayDesignerPage.clickFinish();

        clickAndWait(Locator.linkWithText(assayName));
        clickButton("Import Data");
        clickButton("Next");
        setFormElement(ASSAY_NAME_FIELD_LOCATOR, runName);

        // Use this file as a sample upload file parameter
        setFormElement(Locator.name("myFile"), JAVA_TRANSFORM_SCRIPT);
        setFormElement(AssayConstants.TEXT_AREA_DATA_COLLECTOR_LOCATOR, importData);

        clickButton("Save and Finish");
        assertElementPresent(Locators.labkeyError.containing("Inline warning from R transform."));

        // Verify file parameter is still present. 1 visible + 1 hidden + 2 js texts.
        assertTextPresent(JAVA_TRANSFORM_SCRIPT.getName(), 4);
        assertElementPresent(Locator.linkWithText("remove"));

        assertElementPresent(Locator.linkWithText("Warning link").withAttribute("href", "http://www.labkey.test"));

        File rOutFile = clickAndWaitForDownload(Locator.linkContainingText(R_TRANSFORM_SCRIPT.getName() + "out"));
        File extraFile1 = clickAndWaitForDownload(Locator.linkContainingText("test1.txt"));
        File extraFile2 = clickAndWaitForDownload(Locator.linkContainingText("test2.tsv"));

        String rOut = TestFileUtils.getFileContents(rOutFile);
        assertTrue("Didn't capture R output", rOut.contains("proc.time()"));
        assertEquals("Wrong text in file generated by transform", "This is test file 1 (R).", TestFileUtils.getFileContents(extraFile1).trim());
        assertEquals("Wrong text in file generated by transform", "This is test file 2 (R).", TestFileUtils.getFileContents(extraFile2).trim());

        assertRadioButtonSelected(Locator.id("Previouslyuploadedfiles"));
        clickButton("Proceed");

        clickAndWait(Locator.linkWithText(runName), longWaitForPage);

        // Verify file uploaded
        assertTextPresent(JAVA_TRANSFORM_SCRIPT.getName(), 1);

        DataRegionTable table = new DataRegionTable("Data", this);
        assertEquals(1, table.getDataRowCount());
        assertTextPresent("RWarned");
    }

    @Test
    public void testRTransformInvocationLogging() throws Exception
    {
        String assayName = "transformInvocationLoggingR";
        String importData = "ParticipantId\nRLogged";
        String runName = "R transform logging run";

        // copy the script to a distinct name to avoid upload collisions with the other test methods
        File loggingRScript = TestFileUtils.writeTempFile("transformLogging.R", TestFileUtils.getFileContents(R_TRANSFORM_SCRIPT));

        _assayHelper.createAssayDesign("General", assayName)
                .addTransformScript(loggingRScript, true)
                .clickFinish();

        clickAndWait(Locator.linkWithText(assayName));
        clickButton("Import Data");
        clickButton("Next");
        setFormElement(ASSAY_NAME_FIELD_LOCATOR, runName);
        setFormElement(AssayConstants.TEXT_AREA_DATA_COLLECTOR_LOCATOR, importData);

        Log4jUtils.resetLogMark();
        clickButton("Save and Finish");
        assertElementPresent(Locators.labkeyError.containing("Inline warning from R transform."));

        ScriptInvocationLogHelper.assertScriptLogged((WebDriverWrapper) this, "done", "transform protocol=", "operation=INSERT", assayName);
    }

    @Test
    public void testRTransformUpdateWarning() throws Exception
    {
        String assayName = "transformUpdateWarningR";
        String importData = "ParticipantId\tVisitID\n1\t1";
        String runName = "basic_import_no_transform";

        // copy r_transform_script to a file of different name to avoid name/upload collisions with other test methods
        File updateWarnRScript = TestFileUtils.writeTempFile("transformWarnUpdate.R", TestFileUtils.getFileContents(R_TRANSFORM_SCRIPT));

        // disable the transform on import, enable it on update
        ReactAssayDesignerPage assayDesignerPage = _assayHelper.createAssayDesign("General", assayName)
                .addTransformScript(updateWarnRScript, true);
        assayDesignerPage.setEditableResults(true);
        assayDesignerPage.setEditableRuns(true);
        assayDesignerPage.setScriptActionCheckbox(updateWarnRScript.getName(), Edit, true);
        assayDesignerPage.setScriptActionCheckbox(updateWarnRScript.getName(), Import, false);
        assayDesignerPage.goToResultsFields()
                .addField("comment")
                .setLabel("Comment")
                .setType(FieldDefinition.ColumnType.String);
        assayDesignerPage.clickFinish();

        clickAndWait(Locator.linkWithText(assayName));
        clickButton("Import Data");
        clickButton("Next");
        setFormElement(ASSAY_NAME_FIELD_LOCATOR, runName);
        setFormElement(AssayConstants.TEXT_AREA_DATA_COLLECTOR_LOCATOR, importData);
        clickButton("Save and Finish");

        // edit the result, expect warning
        clickAndWait(Locator.linkWithText(runName));
        DataRegionTable table = new DataRegionTable("Data", this);
        Log4jUtils.resetLogMark();
        table.clickEditRow(0)
                .setField("comment", "commented")
                .submit();

        // note: we currently do not support warnings on update; Issue 52299 tracks this
        // for now, expect warning-generating script events to show up as errors
        assertTextPresent("An error occurred when running the script 'transformWarnUpdate.R', exit code: 1.");

        ScriptInvocationLogHelper.assertScriptLogged((WebDriverWrapper) this, "failed", "transform protocol=", updateWarnRScript.getName());
    }

    @Test
    public void testRTransformError()
    {
        String assayName = "transformErrorR";
        String importData = "ParticipantId\nRError";
        String runName = "R transform run";

        ReactAssayDesignerPage assayDesignerPage = _assayHelper.createAssayDesign("General", assayName)
                .addTransformScript(R_TRANSFORM_ERROR_SCRIPT);
        assayDesignerPage.goToRunFields()
                .addField("myFile")
                .setLabel("My File")
                .setType(FieldDefinition.ColumnType.File);
        assayDesignerPage.clickFinish();

        clickAndWait(Locator.linkWithText(assayName));
        clickButton("Import Data");
        clickButton("Next");
        setFormElement(ASSAY_NAME_FIELD_LOCATOR, runName);

        setFormElement(AssayConstants.TEXT_AREA_DATA_COLLECTOR_LOCATOR, importData);

        clickButton("Save and Finish");
        assertTextPresent("There are errors in the input file");
        assertElementPresent(Locator.tag("td").containing("Col1"));
        assertElementPresent(Locator.tag("td").containing("test2"));
    }

    @Test
    public void testTransformErrorOnUpdate() throws Exception
    {
        String assayName = "transformErrorUpdateR";
        String importData = "ParticipantId\tVisitID\n1\t1";
        String runName = "basic_import_no_transform";

        // copy r_transform_script to a file of different name to avoid name/upload collisions with other test methods
        File updateErrRScript = TestFileUtils.writeTempFile("transformErrUpdate.R", TestFileUtils.getFileContents(R_TRANSFORM_ERROR_SCRIPT));

        // configure the assay to only run the transform on update (not import)
        ReactAssayDesignerPage assayDesignerPage = _assayHelper.createAssayDesign("General", assayName)
                .addTransformScript(updateErrRScript);
        assayDesignerPage.setEditableResults(true);
        assayDesignerPage.setEditableRuns(true);
        assayDesignerPage.setScriptActionCheckbox(updateErrRScript.getName(), Edit, true);
        assayDesignerPage.setScriptActionCheckbox(updateErrRScript.getName(), Import, false);
        assayDesignerPage.goToResultsFields()
                .addField("comment")
                .setLabel("Comment")
                .setType(FieldDefinition.ColumnType.String);
        assayDesignerPage.clickFinish();

        // import a run to edit
        clickAndWait(Locator.linkWithText(assayName));
        clickButton("Import Data");
        clickButton("Next");
        setFormElement(ASSAY_NAME_FIELD_LOCATOR, runName);
        setFormElement(AssayConstants.TEXT_AREA_DATA_COLLECTOR_LOCATOR, importData);

        clickButton("Save and Finish");

        // now edit the run, expect error
        clickAndWait(Locator.linkWithText(runName));
        DataRegionTable table = new DataRegionTable("Data", this);
        table.clickEditRow(0)
                .setField("comment", "commented")
                .submit();

        assertTextPresent("An error occurred when running the script 'transformErrUpdate.R', exit code: 1.");
    }

    @Test
    public void testTransformScriptValidation()
    {
        String assayName = "transformInvalid";
        ReactAssayDesignerPage assayDesignerPage = _assayHelper.createAssayDesign("General", assayName);

        // verify check for valid script engine defined for the file extension
        assayDesignerPage.addTransformScript(JAVA_INVALID_TRANSFORM_SCRIPT, true, "Script engine for the extension '.java' has not been registered.");
        assayDesignerPage.addTransformScript(JAVA_INVALID_TRANSFORM_SCRIPT, false, "Script engine for the extension '.java' has not been registered.");

        // verify check for duplicate file in @scripts dir
        assayDesignerPage.addTransformScript(R_TRANSFORM_ERROR_SCRIPT, true);
        assayDesignerPage.addTransformScript(R_TRANSFORM_ERROR_SCRIPT, true, "File already exists: assayTransformError.R");

        // verify that removing the transform script path does not remove file from file system
        assayDesignerPage.removeTransformScript(R_TRANSFORM_ERROR_SCRIPT.getName());
        WebDavPage webDavPage = WebDavPage.beginAt(this, getProjectName() + "/@scripts");
        webDavPage.getFileBrowserHelper().waitForFileGridReady();
        assertTrue("Transform script file not present in file system.", webDavPage.getFileBrowserHelper().getFileList(false).contains(R_TRANSFORM_ERROR_SCRIPT.getName()));

        // verify file exists in @scripts dir via webdav page
        goToProjectHome();
        impersonateRole(FOLDER_ADMIN_ROLE);
        WebDavPage.beginAt(this, getProjectName() + "/@scripts");
        waitForElement(Locators.labkeyErrorHeading.withText("/_webdav/" + getProjectName() + "/@scripts"));
        stopImpersonatingHTTP();
    }

}
