/*
 * Copyright (c) 2016-2019 LabKey Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.labkey.test.tests.assay;

import org.assertj.core.api.Assertions;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.labkey.test.BaseWebDriverTest;
import org.labkey.test.Locator;
import org.labkey.test.Locators;
import org.labkey.test.TestFileUtils;
import org.labkey.test.TestTimeoutException;
import org.labkey.test.categories.Assays;
import org.labkey.test.categories.Daily;
import org.labkey.test.pages.ReactAssayDesignerPage;
import org.labkey.test.pages.assay.AssayImportPage;
import org.labkey.test.pages.assay.AssayRunsPage;
import org.labkey.test.pages.files.WebDavPage;
import org.labkey.test.params.FieldDefinition;
import org.labkey.test.params.assay.GeneralAssayDesign;
import org.labkey.test.util.DataRegionTable;
import org.labkey.test.util.QCAssayScriptHelper;
import org.labkey.test.util.RReportHelper;

import java.io.File;
import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

@Category({Assays.class, Daily.class})
@BaseWebDriverTest.ClassTimeout(minutes = 4)
public class AssayTransformWarningTest extends BaseWebDriverTest
{
    public static final File JAVA_TRANSFORM_SCRIPT = TestFileUtils.getSampleData("qc/transformWarning.jar");
    public static final File R_TRANSFORM_SCRIPT = TestFileUtils.getSampleData("qc/assayTransformWarning.R");
    public static final File R_TRANSFORM_ERROR_SCRIPT = TestFileUtils.getSampleData("qc/assayTransformError.R");
    public static final File JAVA_INVALID_TRANSFORM_SCRIPT = TestFileUtils.getSampleData("qc/src/org/labkey/AssayTransformNoOp.java");

    @Override
    public List<String> getAssociatedModules()
    {
        return Arrays.asList("assay");
    }

    @Override
    protected String getProjectName()
    {
        return getClass().getSimpleName() + " Project";
    }

    @Override
    protected BrowserType bestBrowser()
    {
        return BrowserType.CHROME;
    }

    @Override
    public void doCleanup(boolean afterTest) throws TestTimeoutException
    {
        _containerHelper.deleteProject(getProjectName(), afterTest);
    }

    @Before
    public void preTest()
    {
        goToProjectHome();
    }

    @BeforeClass
    public static void initTest()
    {
        AssayTransformWarningTest init = (AssayTransformWarningTest)getCurrentTest();
        init.doInit();
    }

    protected void doInit()
    {
        new RReportHelper(this).ensureRConfig();
        new QCAssayScriptHelper(this).ensureEngineConfig();

        _containerHelper.createProject(getProjectName(), "Assay");
    }

    @Test
    public void testJavaTransformWarning()
    {
        String assayName = "transformWarningJar";
        String importData = "ParticipantId\nJavaWarned";
        String runName = "java transform run";

        _assayHelper.createAssayDesign("General", assayName)
            .addTransformScript(JAVA_TRANSFORM_SCRIPT, true)
            .clickFinish();

        clickAndWait(Locator.linkWithText(assayName));
        clickButton("Import Data");
        clickButton("Next");
        setFormElement(Locator.name("name"), runName);
        setFormElement(Locator.name("TextAreaDataCollector.textArea"), importData);

        clickButton("Save and Finish");
        assertElementPresent(Locators.labkeyError.containing("Inline warning from Java transform."));
        assertElementPresent(Locator.linkWithText("Warning link").withAttribute("href", "http://www.labkey.test"));

        File extraFile1 = clickAndWaitForDownload(Locator.linkContainingText("test1.txt"));
        File extraFile2 = clickAndWaitForDownload(Locator.linkContainingText("test2.tsv"));

        assertEquals("Wrong text in file generated by transform", "This is test file 1 (Java).", TestFileUtils.getFileContents(extraFile1).trim());
        assertEquals("Wrong text in file generated by transform", "This is test file 2 (Java).", TestFileUtils.getFileContents(extraFile2).trim());

        clickButton("Proceed");

        clickAndWait(Locator.linkWithText(runName), longWaitForPage);

        DataRegionTable table = new DataRegionTable("Data", this);
        assertEquals(1, table.getDataRowCount());
        assertTextPresent("JavaWarned");
    }

    @Test
    public void testRTransformWarning()
    {
        String assayName = "transformWarningR";
        String importData = "ParticipantId\nRWarned";
        String runName = "R transform run";

        ReactAssayDesignerPage assayDesignerPage = _assayHelper.createAssayDesign("General", assayName)
            .addTransformScript(R_TRANSFORM_SCRIPT, true);
        assayDesignerPage.goToRunFields()
            .addField("myFile")
            .setLabel("My File")
            .setType(FieldDefinition.ColumnType.File);
        assayDesignerPage.clickFinish();

        clickAndWait(Locator.linkWithText(assayName));
        clickButton("Import Data");
        clickButton("Next");
        setFormElement(Locator.name("name"), runName);

        // Use this file as a sample upload file parameter
        setFormElement(Locator.name("myFile"), JAVA_TRANSFORM_SCRIPT);
        setFormElement(Locator.name("TextAreaDataCollector.textArea"), importData);

        clickButton("Save and Finish");
        assertElementPresent(Locators.labkeyError.containing("Inline warning from R transform."));

        // Verify file parameter is still present. 1 visible + 1 hidden + 2 js texts.
        assertTextPresent(JAVA_TRANSFORM_SCRIPT.getName(), 4);
        assertElementPresent(Locator.linkWithText("remove"));

        assertElementPresent(Locator.linkWithText("Warning link").withAttribute("href", "http://www.labkey.test"));

        File rOutFile = clickAndWaitForDownload(Locator.linkContainingText(R_TRANSFORM_SCRIPT.getName() + "out"));
        File extraFile1 = clickAndWaitForDownload(Locator.linkContainingText("test1.txt"));
        File extraFile2 = clickAndWaitForDownload(Locator.linkContainingText("test2.tsv"));

        String rOut = TestFileUtils.getFileContents(rOutFile);
        assertTrue("Didn't capture R output", rOut.contains("proc.time()"));
        assertEquals("Wrong text in file generated by transform", "This is test file 1 (R).", TestFileUtils.getFileContents(extraFile1).trim());
        assertEquals("Wrong text in file generated by transform", "This is test file 2 (R).", TestFileUtils.getFileContents(extraFile2).trim());

        assertRadioButtonSelected(Locator.id("Previouslyuploadedfiles"));
        clickButton("Proceed");

        clickAndWait(Locator.linkWithText(runName), longWaitForPage);

        // Verify file uploaded
        assertTextPresent("assaydata" + File.separator + JAVA_TRANSFORM_SCRIPT.getName(), 1);

        DataRegionTable table = new DataRegionTable("Data", this);
        assertEquals(1, table.getDataRowCount());
        assertTextPresent("RWarned");
    }

    @Test
    public void testRTransformError()
    {
        String assayName = "transformErrorR";
        String importData = "ParticipantId\nRError";
        String runName = "R transform run";

        ReactAssayDesignerPage assayDesignerPage = _assayHelper.createAssayDesign("General", assayName)
                .addTransformScript(R_TRANSFORM_ERROR_SCRIPT);
        assayDesignerPage.goToRunFields()
                .addField("myFile")
                .setLabel("My File")
                .setType(FieldDefinition.ColumnType.File);
        assayDesignerPage.clickFinish();

        clickAndWait(Locator.linkWithText(assayName));
        clickButton("Import Data");
        clickButton("Next");
        setFormElement(Locator.name("name"), runName);

        setFormElement(Locator.name("TextAreaDataCollector.textArea"), importData);

        clickButton("Save and Finish");
        assertTextPresent("There are errors in the input file");
        assertElementPresent(Locator.tag("td").containing("Col1"));
        assertElementPresent(Locator.tag("td").containing("test2"));
    }

    @Test
    public void testTransformScriptValidation()
    {
        String assayName = "transformInvalid";
        ReactAssayDesignerPage assayDesignerPage = _assayHelper.createAssayDesign("General", assayName);

        // verify check for valid script engine defined for the file extension
        assayDesignerPage.addTransformScript(JAVA_INVALID_TRANSFORM_SCRIPT, true, "Script engine for the extension '.java' has not been registered.");
        assayDesignerPage.addTransformScript(JAVA_INVALID_TRANSFORM_SCRIPT, false, "Script engine for the extension '.java' has not been registered.");

        // verify check for duplicate file in @scripts dir
        assayDesignerPage.addTransformScript(R_TRANSFORM_ERROR_SCRIPT, true);
        assayDesignerPage.addTransformScript(R_TRANSFORM_ERROR_SCRIPT, true, "File already exists: assayTransformError.R");

        // verify that removing the transform script path does not remove file from file system
        assayDesignerPage.removeTransformScript(R_TRANSFORM_ERROR_SCRIPT.getName());
        WebDavPage webDavPage = WebDavPage.beginAt(this, getProjectName() + "/@scripts");
        webDavPage.getFileBrowserHelper().waitForFileGridReady();
        assertTrue("Transform script file not present in file system.", webDavPage.getFileBrowserHelper().getFileList(false).contains(R_TRANSFORM_ERROR_SCRIPT.getName()));

        // verify file exists in @scripts dir via webdav page
        goToProjectHome();
        impersonateRole("Folder Administrator");
        WebDavPage.beginAt(this, getProjectName() + "/@scripts");
        waitForElement(Locators.labkeyErrorHeading.withText("/_webdav/" + getProjectName() + "/@scripts"));
        stopImpersonatingHTTP();
    }

    @Test
    public void testEnableTransformForUpdate() throws Exception
    {
        String insertOrUpdateTransform = "insertOrUpdateTransform.R";
        String insertOrUpdateTransformAssay = "insertOrUpdateTransformAssay";
        String transformContent = """
                library(Rlabkey);
                
                run.props = labkey.transform.readRunPropertiesFile("${runInfo}");
                
                run.data.file = labkey.transform.getRunPropertyValue(run.props, "runDataFile");
                run.output.file = run.props$val3[run.props$name == "runDataFile"];
                error.file = labkey.transform.getRunPropertyValue(run.props, "errorsFile");
                
                if (file.exists(run.data.file)) {
                    run.data = read.delim(run.data.file, header=TRUE, sep="\\t");
                    run.data$M2 = 111;
                    run.data$TransformType = "${transformOperation} testing";
                    write.table(run.data, file=run.output.file, sep="\\t", na="", row.names=FALSE, quote=FALSE);
                }
                """;
        File transformFile = TestFileUtils.writeTempFile(insertOrUpdateTransform, transformContent);
        var protocolResponse = new GeneralAssayDesign(insertOrUpdateTransformAssay)
                .setDataFields(List.of(new FieldDefinition("M2", FieldDefinition.ColumnType.Decimal),
                        new FieldDefinition("TransformType", FieldDefinition.ColumnType.String),
                        new FieldDefinition("Comment", FieldDefinition.ColumnType.String)), true)
                .createAssay(getProjectName(), createDefaultConnection());
        goToProjectHome();

        var assayDesignerPage = ReactAssayDesignerPage.beginAt(this, getProjectName(), protocolResponse.getProtocolId(),
                "general", getURL().toString());
        assayDesignerPage.addTransformScript(transformFile, true);

        checker().verifyTrue("expect run on import to be enabled by default",
                assayDesignerPage.isScriptActionCheckboxEnabled(insertOrUpdateTransform, ReactAssayDesignerPage.ScriptFileEvent.Import));
        checker().verifyFalse("expect run on edit not to be enabled by default",
                assayDesignerPage.isScriptActionCheckboxEnabled(insertOrUpdateTransform, ReactAssayDesignerPage.ScriptFileEvent.Edit));
        checker().verifyTrue("expect run on import to be checked by default",
                assayDesignerPage.getScriptActionCheckbox(insertOrUpdateTransform, ReactAssayDesignerPage.ScriptFileEvent.Import));
        checker().verifyFalse("expect run on edit not to be checked by default",
                assayDesignerPage.getScriptActionCheckbox(insertOrUpdateTransform, ReactAssayDesignerPage.ScriptFileEvent.Edit));

        // now enable editable results
        assayDesignerPage.setEditableResults(true);
        checker().verifyTrue("expect run on edit to be enabled when editable results are enabled",
                assayDesignerPage.isScriptActionCheckboxEnabled(insertOrUpdateTransform, ReactAssayDesignerPage.ScriptFileEvent.Edit));

        // check the run on edit box
        assayDesignerPage.setScriptActionCheckbox(insertOrUpdateTransform, ReactAssayDesignerPage.ScriptFileEvent.Edit, true);
        checker().verifyTrue("expect run on edit to be successfully enabled and checked",
                assayDesignerPage.getScriptActionCheckbox(insertOrUpdateTransform, ReactAssayDesignerPage.ScriptFileEvent.Edit));

        // disable editable results and verify that deselects the run on edit box
        assayDesignerPage.setEditableResults(false);
        checker().verifyFalse("expect run on edit to be disabled and deselected when editable results are disabled",
                assayDesignerPage.getScriptActionCheckbox(insertOrUpdateTransform, ReactAssayDesignerPage.ScriptFileEvent.Edit));
        checker().verifyFalse("expect run on edit to be disabled and deselected when editable results are disabled",
                assayDesignerPage.isScriptActionCheckboxEnabled(insertOrUpdateTransform, ReactAssayDesignerPage.ScriptFileEvent.Edit));

        // now re-enable editable results and check run on edit
        assayDesignerPage.setEditableResults(true);
        assayDesignerPage.setScriptActionCheckbox(insertOrUpdateTransform, ReactAssayDesignerPage.ScriptFileEvent.Edit, true);
        assayDesignerPage.clickSave();

        // now import data and ensure the expected transform operation occurred
        String importData = """
                VisitID	ParticipantID	Comment
                1	1	this is the import
                1	2	also import
                """;

        clickAndWait(Locator.linkWithText(insertOrUpdateTransformAssay));
        new AssayRunsPage(getDriver()).getTable().clickHeaderButton("Import Data");
        clickButton("Next");
        var importPage = new AssayImportPage(getDriver());
        importPage.setNamedInputText("name", "transformTestImport");
        importPage.setNamedTextAreaValue("TextAreaDataCollector.textArea", importData);
        importPage.clickSaveAndFinish();

        var assayDataPage = new AssayRunsPage(getDriver()).clickAssayIdLink("transformTestImport");
        var m2Data = assayDataPage.getDataTable().getColumnDataAsText("M2");
        var transformTypeData = assayDataPage.getDataTable().getColumnDataAsText("Transform Type");
        checker().wrapAssertion(()-> Assertions.assertThat(m2Data)
                .as("expect m2Data to contain only hard-coded transform value")
                .containsOnly("111.0"));
        checker().wrapAssertion(()-> Assertions.assertThat(transformTypeData)
                .as("expect transformTypeData to contain only insert")
                .containsOnly("INSERT testing"));
        checker().screenShotIfNewError("unexpected import transform data");

        assayDataPage.getDataTable().clickEditRow(0)
                .setField("Comment", "this is the update")
                .submit();

        var dataMap = assayDataPage.getDataTable().getRowDataAsMap(0);
        checker().verifyEquals("expect dataMap transform to show update",
                "UPDATE testing", dataMap.get("TransformType"));
        checker().screenShotIfNewError("unexpected update transform data");

        // now let's disable both import and edit
        assayDesignerPage = ReactAssayDesignerPage.beginAt(this, getProjectName(), protocolResponse.getProtocolId(),
                "general", getURL().toString());
        assayDesignerPage.setScriptActionCheckbox(transformFile.getName(), ReactAssayDesignerPage.ScriptFileEvent.Edit, false);
        assayDesignerPage.setScriptActionCheckbox(transformFile.getName(), ReactAssayDesignerPage.ScriptFileEvent.Import, false);
        assayDesignerPage.clickSave();

        // now import some data to a new run called non_transform_import
        goToProjectHome();
        clickAndWait(Locator.linkWithText(insertOrUpdateTransformAssay));
        new AssayRunsPage(getDriver()).getTable().clickHeaderButton("Import Data");
        clickButton("Next");
        importPage = new AssayImportPage(getDriver());
        importPage.setNamedInputText("name", "non_transform_import");
        importPage.setNamedTextAreaValue("TextAreaDataCollector.textArea", importData);
        importPage.clickSaveAndFinish();

        var assayDataPage2 = new AssayRunsPage(getDriver()).clickAssayIdLink("non_transform_import");
        var m2Data2 = assayDataPage2.getDataTable().getColumnDataAsText("M2");
        var transformTypeData2 = assayDataPage2.getDataTable().getColumnDataAsText("Transform Type");
        checker().wrapAssertion(()-> Assertions.assertThat(m2Data2)
                .as("expect m2Data not to contain any transform values")
                .containsOnly(" "));
        checker().wrapAssertion(()-> Assertions.assertThat(transformTypeData2)
                .as("expect transformTypeData to contain no transform values")
                .containsOnly(" "));
        checker().screenShotIfNewError("unexpected import transform data");

        // now update the data we just imported
        assayDataPage.getDataTable().clickEditRow(0)
                .setField("Comment", "this is an update but no transform should happen")
                .submit();
        var dataMap2 = assayDataPage.getDataTable().getRowDataAsMap(0);
        checker().verifyEquals("expect dataMap transform data not to appear in transformType field",
                " ", dataMap2.get("TransformType"));
        checker().verifyEquals("expect M2 transform data not to appear in M2 field",
                " ", dataMap2.get("M2"));
        checker().screenShotIfNewError("unexpected update transform data");
    }
}
