package org.labkey.test.params.list;

import org.jetbrains.annotations.NotNull;
import org.labkey.remoteapi.domain.PropertyDescriptor;
import org.labkey.test.params.FieldDefinition;
import org.labkey.test.util.TestDataGenerator;

import java.util.List;

public class IntListDefinition extends ListDefinition
{
    private static final String AUTO_INCREMENT_DOMAIN_KIND = "IntList";

    public IntListDefinition(String name, String autoIncrementKeyName)
    {
        super(name);
        setKeyName(autoIncrementKeyName);
    }

    @Override
    public List<PropertyDescriptor> getFields()
    {
        List<PropertyDescriptor> fields = super.getFields();
        fields.add(0, new FieldDefinition(getKeyName(), FieldDefinition.ColumnType.Integer).setPrimaryKey(true));
        return fields;
    }

    @NotNull
    @Override
    protected String getKind()
    {
        return AUTO_INCREMENT_DOMAIN_KIND;
    }

    @Override
    public TestDataGenerator getTestDataGenerator(String containerPath)
    {
        return super.getTestDataGenerator(containerPath).setAutoGeneratedFields(getKeyName());
    }
}
