package org.labkey.test.params.list;

import org.jetbrains.annotations.NotNull;
import org.labkey.remoteapi.domain.PropertyDescriptor;
import org.labkey.test.params.FieldDefinition;
import org.labkey.test.util.TestDataGenerator;

import java.util.List;

public class IntListDefinition extends ListDefinition
{
    private static final String DOMAIN_KIND = "IntList";

    private final boolean isAutoIncrementKey;

    public IntListDefinition(String name, String autoIncrementKeyName)
    {
        super(name);
        setKeyName(autoIncrementKeyName);
        isAutoIncrementKey = true;
    }

    public IntListDefinition(String name)
    {
        super(name);
        isAutoIncrementKey = false;
    }

    @Override
    public List<PropertyDescriptor> getFields()
    {
        List<PropertyDescriptor> fields = super.getFields();
        if (isAutoIncrementKey)
        {
            fields.add(0, new FieldDefinition(getKeyName(), FieldDefinition.ColumnType.Integer).setPrimaryKey(true));
        }
        return fields;
    }

    @NotNull
    @Override
    protected String getKind()
    {
        return DOMAIN_KIND;
    }

    @Override
    protected String getKeyType()
    {
        return isAutoIncrementKey ? "AutoIncrementInteger" : "Integer";
    }

    @Override
    public TestDataGenerator getTestDataGenerator(String containerPath)
    {
        return super.getTestDataGenerator(containerPath).setAutoGeneratedFields(getKeyName());
    }
}
