package org.labkey.test.params.list;

import org.jetbrains.annotations.NotNull;
import org.labkey.remoteapi.domain.PropertyDescriptor;
import org.labkey.test.params.FieldDefinition;
import org.labkey.test.util.DomainUtils.DomainKind;
import org.labkey.test.util.TestDataGenerator;

import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Supplier;

public class IntListDefinition extends ListDefinition
{

    private final boolean isAutoIncrementKey;

    public IntListDefinition(String name, String autoIncrementKeyName)
    {
        super(name);
        setKeyName(autoIncrementKeyName);
        isAutoIncrementKey = true;
    }

    public IntListDefinition(String name)
    {
        super(name);
        isAutoIncrementKey = false;
    }

    @Override
    public List<PropertyDescriptor> getFields()
    {
        List<PropertyDescriptor> fields = super.getFields();
        if (isAutoIncrementKey)
        {
            fields.addFirst(new FieldDefinition(getKeyName(), FieldDefinition.ColumnType.Integer).setPrimaryKey(true));
        }
        return fields;
    }

    @NotNull
    @Override
    protected String getKind()
    {
        return DomainKind.IntList.name();
    }

    @Override
    protected String getKeyType()
    {
        return isAutoIncrementKey ? "AutoIncrementInteger" : "Integer";
    }

    @Override
    public TestDataGenerator getTestDataGenerator(String containerPath)
    {
        if (isAutoIncrementKey)
        {
            return super.getTestDataGenerator(containerPath).setAutoGeneratedFields(getKeyName());
        }
        else
        {
            // supply key values but ensure they don't collide
            return super.getTestDataGenerator(containerPath).addDataSupplier(getKeyName(), new Supplier<>() {
                private final AtomicInteger keys = new AtomicInteger(1);
                @Override
                public Object get()
                {
                    return keys.getAndIncrement();
                }
            });
        }
    }
}
