/*
 * Copyright (c) 2019 LabKey Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.labkey.test.util;

import org.apache.commons.csv.CSVFormat;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.time.DateUtils;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.junit.Assert;
import org.labkey.api.collections.CaseInsensitiveLinkedHashMap;
import org.labkey.remoteapi.CommandException;
import org.labkey.remoteapi.CommandResponse;
import org.labkey.remoteapi.Connection;
import org.labkey.remoteapi.collections.CaseInsensitiveHashMap;
import org.labkey.remoteapi.domain.CreateDomainCommand;
import org.labkey.remoteapi.domain.DomainResponse;
import org.labkey.remoteapi.domain.PropertyDescriptor;
import org.labkey.remoteapi.query.Filter;
import org.labkey.remoteapi.query.SaveRowsResponse;
import org.labkey.remoteapi.query.SelectRowsResponse;
import org.labkey.remoteapi.query.Sort;
import org.labkey.serverapi.reader.TabLoader;
import org.labkey.test.WebTestHelper;
import org.labkey.test.params.FieldDefinition;
import org.labkey.test.util.data.ColumnNameMapper;
import org.labkey.test.util.data.TestDataUtils;
import org.labkey.test.util.query.QueryApiHelper;

import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import java.util.concurrent.ThreadLocalRandom;
import java.util.function.Supplier;
import java.util.regex.Pattern;

import static org.labkey.test.BaseWebDriverTest.ALL_ILLEGAL_QUERY_KEY_CHARACTERS;
import static org.labkey.test.util.data.TestDataUtils.REALISTIC_ASSAY_FIELDS;
import static org.labkey.test.util.data.TestDataUtils.REALISTIC_SAMPLE_FIELDS;
import static org.labkey.test.util.data.TestDataUtils.REALISTIC_SOURCE_FIELDS;


/**
 * Use this class to generate random test data for a given column schema
 */
public class TestDataGenerator
{
    private static final String WIDE_CHAR = "\uD83D\uDC7E"; // 👾
    private static final char WIDE_PLACEHOLDER = '\u03A0'; // 'Π' - Wide character can't be picked from the string with 'charAt'
    private static final char REPEAT_PLACEHOLDER = '\u22EF'; // '⋯' - Used to indicate that the char will be repeated
    private static final char ALL_CHARS_PLACEHOLDER = '\u2211'; // '∑' - Used to indicate that all characters from the charset should be used
    private static final String NON_LATIN_STRING = "\u0438\uC548\u306F"; // "и안は"
    // chose a Character random from this String
    public static final String CHARSET_STRING = "ABCDEFG01234abcdefvxyz~!@#$%^&*()-+=_{}[]|:;\"',.<>" + NON_LATIN_STRING + WIDE_PLACEHOLDER;
    public static final String ALPHANUMERIC_STRING = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvxyz";
    public static final String DOMAIN_SPECIAL_STRING =  "+- _.:&()/";
    public static final String ILLEGAL_DOMAIN_NAME_CHARSET = "<>[]{};,`\"~!@#$%^*=|?\\";
    // Used to set value of date pickers
    public static final Supplier<SimpleDateFormat> INPUT_DATE_FORMAT = () -> new SimpleDateFormat("MM/dd/yyyy");
    public static final Supplier<SimpleDateFormat> INPUT_DATETIME_FORMAT = () -> new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
    // Default display format
    public static final Supplier<SimpleDateFormat> UI_DATE_FORMAT = () -> new SimpleDateFormat("yyyy-MM-dd");
    public static final Supplier<SimpleDateFormat> UI_DATE_TIME_FORMAT = () -> new SimpleDateFormat("yyyy-MM-dd HH:mm");
    public static final Supplier<SimpleDateFormat> TIME_FORMAT = () -> new SimpleDateFormat("HH:mm:ss");

    private final Map<String, PropertyDescriptor> _columns = new CaseInsensitiveLinkedHashMap<>();
    private final Map<String, Supplier<Object>> _dataSuppliers = new CaseInsensitiveHashMap<>();
    private final Set<String> _autoGeneratedFields = Collections.newSetFromMap(new CaseInsensitiveHashMap<>());
    // Rows generated for next insert or TSV dump
    private final List<Map<String, Object>> _rows = new ArrayList<>();
    // All rows ever generated by this generator
    private final List<Map<String, Object>> _allGeneratedRows = new ArrayList<>();

    private final String _schemaName;
    private final String _queryName;
    private final String _containerPath;
    private String _excludedChars;
    private boolean _alphaNumericStr;

    /**
     *  use TestDataGenerator to generate data to a specific fieldSet
     */
    public TestDataGenerator(String schema, String queryName, String containerPath)
    {
        _schemaName = schema;
        _queryName = queryName;
        _containerPath = containerPath;
    }

    public static File writeCsvFile(List<FieldDefinition> fields, List<Map<String, Object>> entityData, String fileName) throws IOException
    {
        List<List<String>> rows = TestDataUtils.replaceColumnHeaders(
            TestDataUtils.rowListsFromMaps(entityData), ColumnNameMapper.labelToName(fields)); // Use field names

        return TestDataUtils.writeRowsToCsv(fileName, rows);
    }

    public static List<Map<String, Object>> generateEntityData(List<FieldDefinition> fields, String nameField, String namePrefix, int startingCount, int size, boolean addLineage, boolean includeAliquots, String queryName, boolean forGridInsert)
    {
        // Hard to deal with plain PropertyDescriptors and we're unlikely to need to
        List<FieldDefinition> populatableFields = new ArrayList<>(fields);

        populatableFields.removeIf(field -> field.getLookup() != null);

        List<Map<String, Object>> allEntityData = new ArrayList<>();
        for (int i = startingCount; i < (size + startingCount); i++)
        {
            Map<String, Object> entityData = new HashMap<>();

            // Since this will be using the api to populate the sample type need to pass in the column name
            // as it appears in the schema, for example COL_STR_NAME.
            if (nameField != null)
                entityData.put(nameField, namePrefix + i);

            for (FieldDefinition fieldDefinition : populatableFields)
            {
                if (!fieldDefinition.getName().equalsIgnoreCase(nameField)) // Name already set
                {
                    String key = fieldDefinition.getEffectiveLabel();
                    if (fieldDefinition.getType().equals(FieldDefinition.ColumnType.Date))
                        entityData.put(key, UI_DATE_FORMAT.get().format(TestDateUtils.diffFromTodaysDate(Calendar.HOUR, i * 24)));
                    else if (fieldDefinition.getType().equals(FieldDefinition.ColumnType.DateAndTime))
                        entityData.put(key, UI_DATE_TIME_FORMAT.get().format(TestDateUtils.diffFromTodaysDate(Calendar.HOUR, i * 24)));
                    else if (fieldDefinition.getType().equals(FieldDefinition.ColumnType.Time))
                        entityData.put(key, TIME_FORMAT.get().format(TestDateUtils.diffFromTodaysDate(Calendar.HOUR, i * 24)));
                    else if (fieldDefinition.getType().equals(FieldDefinition.ColumnType.Integer))
                    {
                        entityData.put(key, i);
                    }
                    else if (fieldDefinition.getType().equals(FieldDefinition.ColumnType.Decimal))
                    {
                        entityData.put(key, (i + (i * .10)));
                    }
                    else if (fieldDefinition.getType().equals(FieldDefinition.ColumnType.Boolean))
                    {
                        entityData.put(key, i % 2 == 0);
                    }
                    else if (fieldDefinition.getType().equals(FieldDefinition.ColumnType.String))
                    {
                        entityData.put(key, "Entity " + i);
                    }
                    else if (fieldDefinition.getType().equals(FieldDefinition.ColumnType.TextChoice))
                    {
                        FieldDefinition.TextChoiceValidator validator =
                                (FieldDefinition.TextChoiceValidator) fieldDefinition.getValidators().get(0);
                        List<String> textChoices = validator.getValues();
                        int textChoiceIndex = i % textChoices.size();
                        if (forGridInsert)
                            entityData.put(key, List.of(textChoices.get(textChoiceIndex)));
                        else
                            entityData.put(key, textChoices.get(textChoiceIndex));
                    }
                }
            }

            // Caution if you change this code. There are one or two places in the test code that are expecting lineage
            // or aliquots based on this calculation.
            if (addLineage && (i > (size / 2)))
            {
                if (i < size * 0.9 || !includeAliquots)
                {
                    entityData.put("materialInputs/" + queryName, namePrefix + (i - (size / 3)));
                }
                else
                {
                    entityData.put("AliquotedFrom", namePrefix + (i >= size * 0.95 ? 1 : 0));
                }
            }
            allEntityData.add(entityData);
        }
        return allEntityData;
    }

    public static List<FieldDefinition> createSourceTypeFieldList(int numFields, int minNumRandomFields)
    {
        return createFieldList(numFields, minNumRandomFields, REALISTIC_SOURCE_FIELDS);
    }

    public static List<FieldDefinition> createSampleTypeFieldList(int numFields, int minNumRandomFields)
    {
        return createFieldList(numFields, minNumRandomFields, REALISTIC_SAMPLE_FIELDS);
    }

    public static List<FieldDefinition> createAssayDataFieldList(int numFields, int minNumRandomFields)
    {
        return createFieldList(numFields, minNumRandomFields, REALISTIC_ASSAY_FIELDS);
    }

    public static List<FieldDefinition> createFieldList(int numFields, int minNumRandomFields, List<Supplier<
    FieldDefinition>> fieldChoices)
    {
        // first choose numFields - numRandomFields from given field choices
        List<FieldDefinition> fields = new ArrayList<>(shuffleSelect(fieldChoices, Math.min(numFields - minNumRandomFields, fieldChoices.size())).stream().map(Supplier::get).toList());
        // fill in the rest with random field names
        for (int i = 0; i < Math.max(minNumRandomFields, numFields - fields.size()); i++)
        {
            String randomField = randomFieldName(String.format(" random %d ", i + 1));

            FieldDefinition fieldDefinition;
            if (i % 5 == 0)
                fieldDefinition = new FieldDefinition(randomField, FieldDefinition.ColumnType.Decimal);
            else if (i % 5 == 1)
                fieldDefinition = new FieldDefinition(randomField, FieldDefinition.ColumnType.Time);
            else if (i % 5 == 2)
                fieldDefinition = new FieldDefinition(randomField, FieldDefinition.ColumnType.Date);
            else if (i % 5 == 3)
                fieldDefinition = new FieldDefinition(randomField, FieldDefinition.ColumnType.DateAndTime);
            else
                fieldDefinition = new FieldDefinition(randomField, FieldDefinition.ColumnType.Integer);

            fields.add(fieldDefinition);
        }
        Collections.shuffle(fields);

        TestLogger.log("Creating fields: ");
        fields.forEach(obj -> {
            TestLogger.log(obj.getName() + " : " + obj.getType().getLabel());
        });
        return fields;
    }

    public String getSchema()
    {
        return _schemaName;
    }

    public String getQueryName()
    {
        return _queryName;
    }

    public String getContainerPath()
    {
        return _containerPath;
    }

    public void setExcludedChars(String excludedChars)
    {
        _excludedChars = excludedChars;
    }

    public void setAlphaNumericStr(boolean alphaNumericStr)
    {
        _alphaNumericStr = alphaNumericStr;
    }

    /**
     *
     * @param columns   The fieldSet for the domain/sampleset/list.
     */
    public TestDataGenerator withColumns(List<? extends PropertyDescriptor> columns)
    {
        for (PropertyDescriptor fieldDef : columns)
        {
            _columns.put(fieldDef.getName(), fieldDef);
        }
        return this;
    }

    /**
     * Set fields that should be excluded from data generation. Such as intList key or sample name with nameExpression.
     * @param fieldNames fields to exclude
     * @return this
     */
    public TestDataGenerator setAutoGeneratedFields(String... fieldNames)
    {
        _autoGeneratedFields.clear();
        _autoGeneratedFields.addAll(Arrays.asList(fieldNames));

        return this;
    }

    public TestDataGenerator withGeneratedRows(int desiredRowCount)
    {
        if (getRowCount() > 0)
        {
            throw new IllegalStateException("Rows have already been generated");
        }

        generateRows(desiredRowCount);

        return this;
    }

    public TestDataGenerator addDataSupplier(String columnName, Supplier<Object> supplier)
    {
        _dataSuppliers.put(columnName, supplier);
        return this;
    }

    public TestDataGenerator addIntSupplier(String columnName, int min, int max)
    {
        _dataSuppliers.put(columnName, ()-> randomInt(min, max));
        return this;
    }

    public TestDataGenerator addStringSupplier(String columnName, int length)
    {
        _dataSuppliers.put(columnName, ()-> randomString(length, _excludedChars, _alphaNumericStr ? ALPHANUMERIC_STRING : CHARSET_STRING));
        return this;
    }

    /**
     *  // helper to allow adding values as List.of(a, b, c)
     *  Note: this helper uses the indexes of the fieldSet in testDataGenerator, so you can only use this helper
     *  for fields that are explicitly part of the domain.  To add values into off-domain/lookup columns, use @addCustomRow
     * @param values values are mapped to columns in the order the columns were added
     */
    public TestDataGenerator addRow(List<Object> values)
    {
        final ArrayList<String> columns = new ArrayList<>(_columns.keySet()); // _columns remembers insertion order
        Assert.assertEquals("Did not provide the correct size row", columns.size(), values.size());

        Map<String, Object> row = new HashMap<>();
        for (int i = 0; i < values.size(); i++)
        {
            row.put(columns.get(i), values.get(i));
        }
        addCustomRow(row);
        return this;
    }

    public TestDataGenerator addRowsFromFile(File tsv)
    {
        try (TabLoader loader = new TabLoader(tsv, true))
        {
            for (Map<String, Object> row : loader.load())
            {
                addCustomRow(row);
            }
        }
        return this;
    }

    /**
     *  Adds the specified row to the internal collection of rowMaps the object contains.
     *  To insert them to the server, use this.
     *  it is acceptable to add columns that don't exist in the destination, but be careful
     * @param customRow use Map.of(colName1, colValue1 ...)
     */
    public TestDataGenerator addCustomRow(Map<String, Object> customRow)
    {
        customRow = Collections.unmodifiableMap(new CaseInsensitiveHashMap<>(customRow));
        _rows.add(customRow);
        _allGeneratedRows.add(customRow);
        return this;
    }

    public List<Map<String, Object>> getRows()
    {
        return Collections.unmodifiableList(_rows);
    }

    public int getRowCount()
    {
        return _rows.size();
    }

    /**
     * Get all rows previously generated by this instance
     */
    public List<Map<String, Object>> getAllGeneratedRows()
    {
        return _allGeneratedRows;
    }

    public List<PropertyDescriptor> getColumns()
    {
        return new ArrayList<>(_columns.values());
    }

    public void generateRows(int numberOfRowsToGenerate)
    {
        if (_columns.isEmpty())
            throw new IllegalStateException("can't generate row data without column definitions");

        for (int i= 0; i < numberOfRowsToGenerate; i++)
        {
            Map<String, Object> newRow = generateRow();
            addCustomRow(newRow);
        }
    }

    private Map<String, Object> generateRow()
    {
        final Map<String, Object> newRow = new CaseInsensitiveHashMap<>();
        for (String columnName : _columns.keySet())
        {
            if (!_dataSuppliers.containsKey(columnName))
            {
                _dataSuppliers.put(columnName, getDefaultDataSupplier(_columns.get(columnName).getRangeURI()));
            }

            if (_autoGeneratedFields.contains(columnName))
            {
                continue;
            }
            // Generate values
            Object columnValue = _dataSuppliers.get(columnName).get();
            newRow.put(columnName, columnValue);
        }
        return newRow;
    }

    private Supplier<Object> getDefaultDataSupplier(String columnType)
    {
        switch (columnType.substring(columnType.indexOf('#') + 1).toLowerCase())
        {
            case "string":
                return ()-> randomString(20, _excludedChars, _alphaNumericStr ? ALPHANUMERIC_STRING : CHARSET_STRING);
            case "int":
                return ()-> randomInt(0, 20);
            case "float":
                return ()-> randomFloat(0, 20);
            case "double":
                return ()-> randomDouble(0, 20);
            case "boolean":
                return this::randomBoolean;
            case "date":
            case "datetime":
                return ()-> randomDateString(DateUtils.addWeeks(new Date(), -39), new Date());
            case "time":
                return ()->
                    randomInt(0, 23) + ":" + // hour
                        StringUtils.leftPad(String.valueOf(randomInt(0, 59)), 2, "0") + ":" + // minute
                        StringUtils.leftPad(String.valueOf(randomInt(0, 59)), 2, "0") + "." + // second
                        StringUtils.leftPad(String.valueOf(randomInt(0, 999)), 3, "0"); // millisecond
            default:
                throw new IllegalArgumentException("ColumnType " + columnType + " isn't implemented yet");
        }
    }

    public static String randomString(int size)
    {
        return randomString(size, null);
    }

    public static String randomString(int size, @Nullable String exclusion)
    {
        return randomString(size, exclusion, CHARSET_STRING);
    }

    public static String randomString(int size, @Nullable String exclusion, @Nullable String charSet)
    {
        String charSetFrom = StringUtils.isEmpty(charSet) ? CHARSET_STRING : charSet;
        if (!StringUtils.isEmpty(exclusion))
            charSetFrom = charSetFrom.replaceAll("[" + Pattern.quote(exclusion) + "]", "");

        StringBuilder val = new StringBuilder();
        for (int i=0; i<size; i++)
        {
            int randIndex = (int)(charSetFrom.length() * Math.random());
            char c = charSetFrom.charAt(randIndex);
            if (c == REPEAT_PLACEHOLDER)
            {
                randIndex = (int)(charSetFrom.length() * Math.random());
                c = charSetFrom.charAt(randIndex);
                int repeatCount = randomInt(2, 15); // repeat between 2 and 15 times
                val.append(StringUtils.repeat(c, repeatCount));
                break; // we don't want to hit another REPEAT_PLACEHOLDER or ALL_CHARS_PLACEHOLDER in this for loop
            }
            else if (c == ALL_CHARS_PLACEHOLDER)
            {
                val.append(charSetFrom);
                break; // we've added them all, no need to continue, and we don't want to hit another REPEAT_PLACEHOLDER or ALL_CHARS_PLACEHOLDER in this for loop
            }
            else if (c == WIDE_PLACEHOLDER)
                val.append(WIDE_CHAR);
            else
                val.append(c);
        }
        return val.toString();
    }

    public static String randomMultiLineString(int size)
    {
        return randomMultiLineString(size, null);
    }

    public static String randomMultiLineString(int size, @Nullable String exclusion)
    {
        return randomString(size, exclusion, CHARSET_STRING + "\t\n\n\n");
    }

    /**
     * Creates a String containing the given part with random characters from charSet surrounding it. The name
     * will have leading and trailing spaces removed and multiple internal spaces collapsed to a single space
     * in order to be compatible with UI display. Because of this space treatment, there may be fewer than the
     * specified number of characters before and after the given part.
     *
     * @param part          the part that is to be included between random strings
     * @param numStartChars maximum number of random characters from charSet
     * @param numEndChars   maximum number of random characters from charSet at the end of the string
     * @param charSet       the set of characters to draw randomly from
     * @param exclusions    characters that are to be excluded from the random parts of the name
     * @return a name with given characters that will be displayed as returned in the UI.
     */
    public static String randomName(@NotNull String part, int numStartChars, int numEndChars, String charSet, @Nullable String exclusions)
    {
        return (randomString(numStartChars, exclusions, charSet) + part + randomString(numEndChars, exclusions, charSet)).trim();
    }

    public static String randomDomainName()
    {
        return randomDomainName(null);
    }

    public static String randomDomainName(@Nullable String part)
    {
        return randomDomainName(part, randomInt(0, 10));
    }

    public static String randomInvalidDomainName(@Nullable String namePart, int numStartChars, int numEndChars)
    {
        String domainName = randomName(namePart == null ? "" : namePart, numStartChars, numEndChars, ILLEGAL_DOMAIN_NAME_CHARSET, null);
        TestLogger.log("Generated random invalid domain name: " + domainName);
        return domainName;
    }

    public static String randomDomainName(int numEndChars)
    {
        return randomDomainName(null, numEndChars);
    }

    /**
     * Generate a random domain name of the specified size.
     *
     * @param namePart    If a namePart is provided, the domain name will contain it. Pass null to generate a random alphanumeric single character for the prefix.
     * @param numEndChars Number of random characters at end of name
     * @return name containing the given name part and appended random characters that should be a valid domain name
     */
    public static String randomDomainName(@Nullable String namePart, int numEndChars)
    {
        String domainName;
        do
        {
            String firstChar = namePart != null ? namePart.charAt(0) + "" : randomString(1, null, ALPHANUMERIC_STRING); // domain needs to start with alphanumeric char;
            String _namePart = namePart != null ? namePart.substring(1) : "";
            final String charset = namePart != null ? DOMAIN_SPECIAL_STRING : ALPHANUMERIC_STRING + DOMAIN_SPECIAL_STRING;
            domainName = firstChar + randomName(_namePart, 0, numEndChars, charset, null);
        }
        while (Pattern.matches("(.*\\s--[^ ].*)|(.*\\s-[^- ].*)", domainName)); // domain name must not contain space followed by dash. (command like: Issue 49161)

        // Multiple spaces in the UI are collapsed into a single space. If we need to test for handling of multiple spaces, we'll not use this generator
        domainName = domainName.replaceAll("\\s+", " ");

        TestLogger.log("Generated random domain name: " + domainName);
        return domainName;
    }

    public static String randomFieldName(String part)
    {
        return randomFieldName(part, null);
    }

    public static String randomFieldName(String part, @Nullable String exclusion)
    {
        return randomFieldName(part, randomInt(0, 5), randomInt(0, 5), exclusion);
    }

    public static String randomFieldName(String part, int numStartChars, int numEndChars)
    {
       return randomFieldName(part, numStartChars, numEndChars, null);
    }

    public static String randomFieldName(@NotNull String part, int numStartChars, int numEndChars, @Nullable String exclusion)
    {
        // use the characters that we know are encoded in fieldKeys plus characters that we know clients are using
        // Issue 53197: Field name with double byte character can cause client side exception in Firefox when trying to customize grid view.
        String chars = ALL_ILLEGAL_QUERY_KEY_CHARACTERS + " %()=+-[]_|*`'\":;<>?!@#^" + NON_LATIN_STRING
                + WIDE_PLACEHOLDER + REPEAT_PLACEHOLDER + ALL_CHARS_PLACEHOLDER;

        String randomFieldName = randomName(part, numStartChars, numEndChars, chars, exclusion);

        // Avoid generating fields names with reserved substitution format patterns. e.g. ":Date" or ":First"
        if (numStartChars > 0 && part.length() >= 4 && randomFieldName.charAt(numStartChars - 1) == ':' &&
                StringUtils.isAlpha(part.substring(0, 4))) // The shortest pattern is four characters (see org.labkey.api.util.SubstitutionFormat.getFormatNames)
        {
            String regenExclusion = Objects.requireNonNullElse(exclusion, "") + ":";
            randomFieldName = randomFieldName.substring(0, numStartChars - 1) +
                    randomString(1, regenExclusion, chars) +
                    randomFieldName.substring(numStartChars + 1);
        }

        TestLogger.log("Generated random field name: " + randomFieldName);
        return randomFieldName;
    }

    public static String randomChoice(List<String> choices)
    {
        return choices.get(randomInt(0, choices.size() - 1));
    }

    public static int randomInt(int min, int max)
    {
        if (min >= max)
            throw new IllegalArgumentException("min must be less than max");

        return ThreadLocalRandom.current().nextInt((max - min) + 1) + min;
    }

    public float randomFloat(float min, float max)
    {
        if (min >= max)
            throw new IllegalArgumentException("min must be less than max");

        return  min + ThreadLocalRandom.current().nextFloat() * (max - min);
    }

    public Double randomDouble(double min, double max)
    {
        if (min >= max)
            throw new IllegalArgumentException("min must be less than max");

        return  min + ThreadLocalRandom.current().nextDouble() * (max - min);
    }

    public String randomDateString(Date min, Date max)
    {
        return randomDateString("yyyy-MM-dd HH:mm", min, max);
    }

    /*
     * simple way to get a dateformat:  (String)executeScript("return LABKEY.container.formats.dateTimeFormat");
     * */
    public String randomDateString(String dateFormat, Date min, Date max)
    {
        long random = ThreadLocalRandom.current().nextLong(min.getTime(), max.getTime());
        Date date = new Date(random);
        return new SimpleDateFormat(dateFormat).format(date);
    }

    public boolean randomBoolean()
    {
        return ThreadLocalRandom.current().nextBoolean();
    }

    private @NotNull List<String> getFieldsForFile()
    {
        List<String> fieldNames = new ArrayList<>(_columns.keySet());
        fieldNames.removeAll(_autoGeneratedFields);
        return fieldNames;
    }

    /**
     * Get generated data for the specified column.
     * Values will be quoted appropriately for pasting into editable grid lookups.
     */
    public List<String> getPasteColumnValues(String fieldName)
    {
        List<String> values = new ArrayList<>();
        for (Map<String, Object> row : _rows)
        {
            Object value = row.get(fieldName);
            String strVal = CSVFormat.DEFAULT.format(value); // Just quote commas
            values.add(strVal);
        }
        return values;
    }

    /**
     * generates tsv-formatted content using the rows in the current instance;
     * @return TSV formatted representation of generated data
     */
    public String getDataAsTsv()
    {
        return TestDataUtils.stringFromRowMaps(_rows, getFieldsForFile(), true, CSVFormat.TDF);
    }

    /**
     * Creates a file containing the contents of the current rows, formatted in TSV, CSV, or xlsx.
     * The file is written to the test temp dir
     * @param fileName  the name of the file, e.g. 'testDataFileForMyTest.tsv'
     * @return File object pointing at created file
     */
    public File writeData(String fileName)
    {
        return writeData(fileName, new FileRowIterator(getFieldsForFile(), _rows));
    }

    /**
     * Generate rows and write to file without saving in data generator
     * @param fileName the name of the file, e.g. 'testDataFileForMyTest.tsv'
     * @param numRows the number of rows to generate
     * @return object pointing at created file
     */
    public File writeData(String fileName, int numRows)
    {
        return writeData(fileName, new FileRowIterator(getFieldsForFile(), this::generateRow, numRows));
    }

    /**
     * Creates a file containing the contents of the current rows, formatted in TSV, CSV, or xlsx.
     * The file is written to the test temp dir
     * @param fileName  the name of the file, e.g. 'testDataFileForMyTest.tsv'
     * @return File object pointing at created file
     */
    public File writeData(String fileName, Iterator<List<Object>> rowIterator)
    {
        try
        {
            return TestDataUtils.writeRowsToFile(fileName, rowIterator);
        }
        catch (IOException e)
        {
            throw new RuntimeException(e);
        }
    }

    /**
     * @deprecated Use {@link org.labkey.test.params.property.DomainProps#create(Connection, String)}
     */
    @Deprecated (since = "22.4")
    public DomainResponse createDomain(Connection cn, String domainKind) throws IOException, CommandException
    {
        return createDomain(cn, domainKind, null);
    }

    /**
     * @deprecated Use {@link org.labkey.test.params.property.DomainProps#create(Connection, String)}
     */
    @Deprecated (since = "22.4")
    public DomainResponse createDomain(Connection cn, String domainKind, Map<String, Object> domainOptions) throws IOException, CommandException
    {
        CreateDomainCommand cmd = new CreateDomainCommand(domainKind, getQueryName());
        cmd.getDomainDesign().setFields(new ArrayList<>(getColumns()));

        if (domainOptions!= null)
            cmd.setOptions(domainOptions);

        return cmd.execute(cn, _containerPath);
    }

    /**
     * @deprecated Use {@link org.labkey.test.params.list.IntListDefinition#create(Connection, String)}
     */
    @Deprecated (since = "22.4")
    public DomainResponse createList(Connection cn, String keyName) throws IOException, CommandException
    {
        return createDomain(cn, "IntList", Map.of("keyName", keyName));
    }

    /**
     * @deprecated Use {@link QueryApiHelper}
     */
    @Deprecated(since = "22.4")
    public CommandResponse deleteDomain(Connection cn) throws IOException, CommandException
    {
        return getQueryHelper(cn).deleteDomain();
    }

    public SaveRowsResponse insertRows() throws IOException, CommandException
    {
        return insertRows(WebTestHelper.getRemoteApiConnection());
    }

    public SaveRowsResponse insertRows(Connection cn) throws IOException, CommandException
    {
        return insertRows(cn, getRows());
    }

    public SaveRowsResponse insertRows(Connection cn, List<Map<String, Object>> rows) throws IOException, CommandException
    {
        return getQueryHelper(cn).insertRows(rows);
    }

    public static <T> List<T> shuffleSelect(List<T> allFields, int selectCount)
    {
        List<T> shuffled = new ArrayList<>(allFields);
        Collections.shuffle(shuffled);
        return shuffled.subList(0, selectCount);
    }

    public static <T> List<T> randomSelect(List<T> allOptions, int selectCount)
    {
        List<T> selected = new ArrayList<>();
        for (int i = 0; i < selectCount; i++)
        {
            selected.add(allOptions.get(randomInt(0, allOptions.size())));
        }
        return selected;
    }

    /**
     * @deprecated Use {@link QueryApiHelper}
     */
    @Deprecated(since = "22.4")
    public SaveRowsResponse updateRows(Connection cn, List<Map<String, Object>> rows) throws IOException, CommandException
    {
        return getQueryHelper(cn).updateRows(rows);
    }

    /**
     * @deprecated Use {@link QueryApiHelper}
     */
    @Deprecated(since = "22.4")
    public SelectRowsResponse getRowsFromServer(Connection cn) throws IOException, CommandException
    {
        return getQueryHelper(cn).selectRows();
    }

    /**
     * @deprecated Use {@link QueryApiHelper}
     */
    @Deprecated(since = "22.4")
    public SelectRowsResponse getRowsFromServer(Connection cn, List<String> intendedColumns) throws IOException, CommandException
    {
        return getQueryHelper(cn).selectRows(intendedColumns);
    }

    /**
     * @deprecated Use {@link QueryApiHelper}
     */
    @Deprecated(since = "22.4")
    public SelectRowsResponse getRowsFromServer(Connection cn, List<String> intendedColumns, @Nullable  List<Filter> filters) throws IOException, CommandException
    {
        return getQueryHelper(cn).selectRows(intendedColumns, filters);
    }

    /**
     * @deprecated Use {@link QueryApiHelper}
     */
    @Deprecated(since = "22.4")
    public SelectRowsResponse getRowsFromServer(Connection cn, List<String> intendedColumns, @Nullable  List<Filter> filters, @Nullable List<Sort> sorts) throws IOException, CommandException
    {
        return getQueryHelper(cn).selectRows(intendedColumns, filters, sorts);
    }

    /**
     * @deprecated Use {@link QueryApiHelper}
     */
    @Deprecated(since = "22.4")
    public SaveRowsResponse deleteRows(Connection cn, List<Map<String,Object>> rowsToDelete) throws IOException, CommandException
    {
        return getQueryHelper(cn).deleteRows(rowsToDelete);
    }

    public QueryApiHelper getQueryHelper(Connection connection)
    {
        return new QueryApiHelper(connection, _containerPath, _schemaName, _queryName);
    }

    public TestDataValidator getValidator()
    {
        return new TestDataValidator(_allGeneratedRows);
    }

    /**
     * @deprecated Inline this.
     */
    @Deprecated (since = "20.4")
    static public FieldDefinition simpleFieldDef(String name, FieldDefinition.ColumnType type)
    {
        return new FieldDefinition(name, type);
    }

    /**
     * @deprecated Moved to {@link DomainUtils#deleteDomain(String, String, String)}
     */
    @Deprecated (since = "22.4")
    public static CommandResponse deleteDomain(final String containerPath, final String schema,
                                                 final String queryName)
            throws CommandException
    {
        return DomainUtils.deleteDomain(containerPath, schema, queryName);
    }

    /**
     * @deprecated Moved to {@link DomainUtils#doesDomainExist(String, String, String)}
     */
    @Deprecated (since = "22.4")
    public static boolean doesDomainExists(final String containerPath, final String schema,
                                                final String queryName)
    {
        return DomainUtils.doesDomainExist(containerPath, schema, queryName);
    }

}

class FileRowIterator implements Iterator<List<Object>>
{
    private final List<String> headers;
    private final Iterator<Map<String, Object>> rows;

    private boolean firstRow = true;

    public FileRowIterator(@NotNull List<String> headers, @NotNull Iterator<Map<String, Object>> rows)
    {
        this.headers = Objects.requireNonNull(headers);
        this.rows = Objects.requireNonNull(rows);
    }

    public FileRowIterator(@NotNull List<String> headers, @NotNull Supplier<Map<String, Object>> rowSupplier, final int rowCount)
    {
        this(headers, new Iterator<>()
        {
            int count = 0;

            @Override
            public boolean hasNext()
            {
                return count < rowCount;
            }

            @Override
            public Map<String, Object> next()
            {
                count++;
                return rowSupplier.get();
            }
        });
    }

    public FileRowIterator(@NotNull List<String> headers, @NotNull List<Map<String, Object>> rows)
    {
        this(headers, rows.iterator());
    }

    @Override
    public boolean hasNext()
    {
        return firstRow || rows.hasNext();
    }

    @Override
    public List<Object> next()
    {
        if (!hasNext())
            throw new NoSuchElementException();

        if (firstRow)
        {
            firstRow = false;
            return Collections.unmodifiableList(headers);
        }
        else
        {
            return rowMapToList(rows.next());
        }
    }

    private List<Object> rowMapToList(Map<String, Object> row)
    {
        return headers.stream().map(h -> row.getOrDefault(h, "")).toList();
    }
}