/*
 * Copyright (c) 2025-2026 LabKey Corporation
 *
 * Licensed under the Apache License, Version 2.0: http://www.apache.org/licenses/LICENSE-2.0
 */
DROP TABLE IF EXISTS vehicle.OwnedVehicles;
DROP TABLE IF EXISTS vehicle.Owners;

CREATE TABLE vehicle.Owners
(
    RowId BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2147483648 INCREMENT BY 1),
    Name VARCHAR(100) NOT NULL,

    CONSTRAINT PK_Owners PRIMARY KEY (RowId)
);

CREATE TABLE vehicle.OwnedVehicles
(
    RowId BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 4294967296 INCREMENT BY 1),
    Owner BIGINT NOT NULL,
    Vehicle INT NOT NULL,

    CONSTRAINT PK_OwnedVehicles PRIMARY KEY (RowId)
);